#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Main Build Orchestrator

on:
  push:
    branches: [main]

env: 
  BUILD_VERSION: 0.0.0

jobs:
  calculate-galasa-semantic-version:
    runs-on: ubuntu-latest
    outputs:
      GALASA_VERSION: ${{ steps.calculate-galasa-version }}
    steps:
      - name: calculate-galasa-version
        run: | 
          echo "GALASA_VERSION=0.40.0" >> $GITHUB_OUTPUT

  echo-version:
    needs: calculate-galasa-semantic-version
    runs-on: ubuntu-latest
    steps:
      - name: show the version
        run: |
          echo "Version is ${{needs.calculate-galasa-semantic-version.outputs.GALASA_VERSION}}"



  
