#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Main Build Orchestrator

on:
  push:
    branches: [main]

env: 
  GALASA_VERSION: "0.39.0"

jobs:
  calculate-galasa-semantic-version:
    runs-on: ubuntu-latest
    outputs:
      GALASA_VERSION: ${{ steps.calculate-galasa-version.outputs.GALASA_VERSION }}
    steps:
      - id: calculate-galasa-version
        run: | 
          echo "GALASA_VERSION=0.40.0" >> $GITHUB_OUTPUT

  echo-environmental-version:
    runs-on: ubuntu-latest
    steps:
      - id: show-the-version
        run: |
          echo "Version is ${{env.GALASA_VERSION}}"

  echo-calculated-version:
    needs: calculate-galasa-semantic-version
    runs-on: ubuntu-latest
    steps:
      - id: show-the-version
        run: |
          echo "Version is ${{needs.calculate-galasa-semantic-version.outputs.GALASA_VERSION}}"

  invoke-subflow:
    name: Invoke the subflow
    uses: ./.github/workflows/subflow.yaml
    secrets: inherit
  
