#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Main Build Orchestrator

on:
  push:
    branches: [main]

env: 
  BUILD_VERSION: 0.0.0

jobs:
  calculate-semantic-version:
    runs-on: ubuntu-latest
    steps:
      - name: calculate version
        run: | 
          echo "BUILD_VERSION=0.40.0" >> $GITHUB_ENV

  echo-version:
    needs: calculate-semantic-version
    runs-on: ubuntu-latest
    steps:
      - name: show the version
        run: |
          echo "Version is ${BUILD_VERSION}"



  
