name: Managers PR Build

on:
  workflow_call:  
    inputs:
      GALASA_VERSION:
        type: string
        required: true

jobs:

  show-the-passed-version:
    runs-on: ubuntu-latest
    steps:
      - id: show-the-passed-version
        run: |
          echo "Version is ${{inputs.GALASA_VERSION}}"